export const teachers = [
  {
    id: '1',
    name: 'Dr. Sarah Jenkins',
    title: 'Senior Mathematics Professor',
    subjects: ['Mathematics', 'Statistics', 'Calculus'],
    major: 'Education',
    rating: 4.9,
    reviewCount: 312,
    students: 1240,
    location: 'Phnom Penh',
    experience: 12,
    verified: true,
    online: true,
    bio: 'Over 12 years of experience teaching advanced mathematics at university level. Specializes in making complex topics accessible and engaging for all learners.',
    price: 45,
  },
  {
    id: '2',
    name: 'Dr. Phe Sophy',
    title: 'Senior Professor of Data Science',
    subjects: ['Data Science', 'Machine Learning', 'Python', 'SQL'],
    major: 'Data Science',
    rating: 4.8,
    reviewCount: 256,
    students: 980,
    location: 'Siem Reap',
    experience: 8,
    verified: true,
    online: false,
    bio: 'Passionate data scientist with expertise in ML algorithms and big data analytics. Published researcher with 20+ academic papers.',
    price: 55,
  },
  {
    id: '3',
    name: 'Dr. James Wilson',
    title: 'Mathematics & Theoretical Physics',
    subjects: ['Physics', 'Mathematics', 'Quantum Mechanics'],
    major: 'Mechanical Engineering',
    rating: 4.7,
    reviewCount: 189,
    students: 756,
    location: 'Battambang',
    experience: 15,
    verified: true,
    online: true,
    bio: 'Theoretical physicist combining rigorous academia with practical teaching. Expert at building intuition for abstract concepts.',
    price: 60,
  },
  {
    id: '4',
    name: 'Ms. Linda Chea',
    title: 'English Language & Literature',
    subjects: ['English', 'IELTS', 'Writing'],
    major: 'English',
    rating: 4.6,
    reviewCount: 421,
    students: 1890,
    location: 'Phnom Penh',
    experience: 6,
    verified: true,
    online: true,
    bio: 'CELTA certified English teacher focused on practical communication skills and exam preparation.',
    price: 30,
  },
  {
    id: '5',
    name: 'Mr. Sokha Dara',
    title: 'Computer Science & Web Development',
    subjects: ['Programming', 'Web Dev', 'React', 'JavaScript', 'Node JS', 'Java'],
    major: 'Information Technology',
    rating: 4.5,
    reviewCount: 178,
    students: 634,
    location: 'Kampong Cham',
    experience: 5,
    verified: false,
    online: false,
    bio: 'Full-stack developer turned educator. Passionate about making coding accessible to beginners through project-based learning.',
    price: 35,
  },
]

export const notifications = [
  {
    id: '1',
    type: 'booking',
    title: 'Session Confirmed',
    message: 'Your session with Dr. Sarah Jenkins is confirmed for tomorrow at 10:00 AM.',
    time: '2 min ago',
    read: false,
  },
  {
    id: '2',
    type: 'message',
    title: 'New Message',
    message: 'Dr. Phe Sophy sent you a message: "Looking forward to our session!"',
    time: '1 hour ago',
    read: false,
  },
  {
    id: '3',
    type: 'review',
    title: 'Review Request',
    message: 'How was your session with Dr. James Wilson? Leave a review to help others.',
    time: '3 hours ago',
    read: true,
  },
  {
    id: '4',
    type: 'promo',
    title: 'Special Offer',
    message: 'Get 20% off your next 3 sessions! Offer expires in 48 hours.',
    time: '1 day ago',
    read: true,
  },
  {
    id: '5',
    type: 'system',
    title: 'Profile Reminder',
    message: 'Complete your profile to get personalized teacher recommendations.',
    time: '2 days ago',
    read: true,
  },
]

export const scheduleEvents = [
  {
    id: '1',
    teacher: teachers[0],
    date: '2026-05-20',
    time: '10:00 AM',
    duration: 60,
    subject: 'Calculus',
    status: 'upcoming',
  },
  {
    id: '2',
    teacher: teachers[1],
    date: '2026-05-21',
    time: '2:00 PM',
    duration: 90,
    subject: 'Machine Learning',
    status: 'upcoming',
  },
  {
    id: '3',
    teacher: teachers[2],
    date: '2026-05-18',
    time: '11:00 AM',
    duration: 60,
    subject: 'Quantum Physics',
    status: 'completed',
  },
  {
    id: '4',
    teacher: teachers[3],
    date: '2026-05-17',
    time: '3:00 PM',
    duration: 45,
    subject: 'IELTS Writing',
    status: 'completed',
  },
]

export { browseCommunities as communities, allCommunities, featuredCommunities } from '../constants/communities'
