/** Khmer display labels for filter dropdown values (values stay English for API/logic). */
const kmOptionLabels = {
  'All Types': 'គ្រប់ប្រភេទ',
  'All Majors': 'គ្រប់ជំនាញ',
  'All Subjects': 'គ្រប់មុខវិជ្ជា',
  'All Provinces': 'គ្រប់ខេត្ត',
  'Any Time': 'ពេលវេលាណាមួយ',
  'Best Match': 'ផ្គូផ្គងល្អបំផុត',
  'Highest Rated': 'ពិន្ទុខ្ពស់បំផុត',
  'Most Popular': 'ពេញនិយមបំផុត',
  Newest: 'ថ្មីបំផុត',
  'Most Reviewed': 'មានការវាយតម្លៃច្រើនបំផុត',
  'Price: Low to High': 'តម្លៃទាបដណ្តើមខ្ពស់',
  'Price: High to Low': 'តម្លៃខ្ពស់ដណ្តើមទាប',
  'Nearest Location': 'ទីតាំងជិតបំផុត',
  'Most Students': 'សិស្សច្រើនបំផុត',
  'Top Recommended': 'ណែនាំកំពូល',
  Private: 'មេរៀនឯកជន',
  Group: 'មេរៀនក្រុម',
  'Private Math': 'គណិតវិទ្យាឯកជន',
  'Group Science': 'វិទ្យាសាស្ត្រក្រុម',
  'Information Technology': 'បច្ចេកវិទ្យាព័ត៌មាន',
  'Computer Science': 'វិទ្យាសាស្ត្រកុំព្យូទ័រ',
  'Software Engineering': 'វិស្វកម្មសូហ្វវែ',
  'Computer Engineering': 'វិស្វកម្មកុំព្យូទ័រ',
  Business: 'ពាណិជ្ជកម្ម',
  Accounting: 'គណនេយ្យ',
  Economics: 'សេដ្ឋកិច្ច',
  Finance: 'ហិរញ្ញវត្ថុ',
  Marketing: 'ទីផ្សារ',
  Management: 'គ្រប់គ្រង',
  'Digital Marketing': 'ទីផ្សារឌីជីថល',
  'Data Science': 'វិទ្យាទិន្នន័យ',
  'Cyber Security': 'សុវត្ថិភាព 사이ber',
  'Artificial Intelligence': 'បញ្ញាសត្វ',
  Chemistry: 'គីមី',
  Biology: 'ជីវវិទ្យា',
  History: 'ប្រវត្តិសាស្ត្រ',
  Programming: 'ការសរសេរកូដ',
  'Web Dev': 'អភិវឌ្ឍគេហទំព័រ',
  React: 'React',
  'Quantum Mechanics': 'Quantum Mechanics',
  IELTS: 'IELTS',
  Writing: 'អក្សរសាស្ត្រ',
  'Grade 7': 'ថ្នាក់ ៧',
  'Grade 8': 'ថ្នាក់ ៨',
  'Grade 9': 'ថ្នាក់ ៩',
  'Grade 10': 'ថ្នាក់ ១០',
  'Grade 11': 'ថ្នាក់ ១១',
  'Grade 12': 'ថ្នាក់ ១២',
  'Network Engineering': 'វិស្វកម្មបណ្តាញ',
  'Graphic Design': 'រចនាក្រាហ្វិក',
  Architecture: 'ស្ថាបត្យកម្ម',
  Education: 'អប់រំ',
  English: 'ភាសាអង់គ្លេស',
  Law: 'ច្បាប់',
  Medicine: 'វេជ្ជសាស្ត្រ',
  'Civil Engineering': 'វិស្វកម្មសំណង់',
  'Electrical Engineering': 'វិស្វកម្មអគ្គិសនី',
  'Mechanical Engineering': 'វិស្វកម្មមេកានិក',
  Java: 'Java',
  JavaScript: 'JavaScript',
  'Node JS': 'Node JS',
  'React JS': 'React JS',
  'Next JS': 'Next JS',
  'Vue JS': 'Vue JS',
  Angular: 'Angular',
  Python: 'Python',
  PHP: 'PHP',
  Laravel: 'Laravel',
  'C#': 'C#',
  '.NET': '.NET',
  'C++': 'C++',
  C: 'C',
  SQL: 'SQL',
  MySQL: 'MySQL',
  PostgreSQL: 'PostgreSQL',
  MongoDB: 'MongoDB',
  'Data Structures': 'រចនាសម្ព័ន្ធទិន្នន័យ',
  Algorithms: 'ក្បួនដោះស្រាយ',
  'UI/UX Design': 'រចនា UI/UX',
  'Machine Learning': 'Machine Learning',
  Networking: 'បណ្តាញ',
  'Mobile Development': 'អភិវឌ្ឍកម្មវិធីទូរស័ព្ទ',
  Flutter: 'Flutter',
  Android: 'Android',
  iOS: 'iOS',
  Mathematics: 'គណិតវិទ្យា',
  Physics: 'រូបវិទ្យា',
  Statistics: 'ស្ថិតិ',
  Calculus: 'Calculus',
  'Phnom Penh': 'ភ្នំពេញ',
  'Siem Reap': 'សៀមរាប',
  Battambang: 'បាត់ដំបង',
  'Banteay Meanchey': 'បន្ទាយមានជ័យ',
  'Kampong Cham': 'កំពង់ចាម',
  'Kampong Chhnang': 'កំពង់ឆ្នាំង',
  'Kampong Speu': 'កំពង់ស្ពឺ',
  'Kampong Thom': 'កំពង់ធំ',
  Kampot: 'កំពត',
  Kandal: 'កណ្តាល',
  Kep: 'កែប',
  'Koh Kong': 'កោះកុង',
  Kratie: 'ក្រចេះ',
  Mondulkiri: 'មណ្ឌលគិរី',
  'Oddar Meanchey': 'ឧត្តរមានជ័យ',
  Pailin: 'ប៉ៃលិន',
  'Preah Sihanouk': 'ព្រះសីហនុ',
  'Preah Vihear': 'ព្រះវិហារ',
  'Prey Veng': 'ព្រៃវែង',
  Pursat: 'ពោធិ៍សាត់',
  Ratanakiri: 'រតនគិរី',
  'Stung Treng': 'ស្ទឹងត្រែង',
  'Svay Rieng': 'ស្វាយរៀង',
  Takeo: 'តាកែវ',
  'Tbong Khmum': 'ត្បូងឃ្មុំ',
}

export default kmOptionLabels
